// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.API.Data;

#nullable disable

namespace TaskManager.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240118062817_datatest")]
    partial class datatest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.API.Models.Domain.TaskM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskMs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            DueDate = new DateTime(2024, 1, 18, 11, 58, 17, 807, DateTimeKind.Local).AddTicks(9848),
                            Title = "Task 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            DueDate = new DateTime(2024, 1, 19, 11, 58, 17, 807, DateTimeKind.Local).AddTicks(9869),
                            Title = "Task 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
