// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.API.Data;

#nullable disable

namespace TaskManager.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.API.Models.Domain.TaskM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskMs");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Description = "Implement RESTful API for the project",
                            DueDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Develop RESTful API"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Create database schema for the application",
                            DueDate = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Design Database Schema"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Integrate user authentication using OAuth 2.0",
                            DueDate = new DateTime(2024, 1, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Implement User Authentication"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Review and optimize the existing codebase",
                            DueDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Optimize Codebase"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Create unit tests for critical components",
                            DueDate = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Write Unit Tests"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
